import { useMemo, useState, type JSX } from "react";
import { useQuery } from "@tanstack/react-query";
import { openUrl } from "@tauri-apps/plugin-opener";
import licensesData from "../assets/third-party-licenses.json";
import Logo from "../components/Logo";
import { api } from "../lib/api";
import "./screens.css";

interface LicenseEntry {
  name: string;
  version: string;
  license: string;
}

const licenses: LicenseEntry[] = licensesData as LicenseEntry[];

/** Regenerated by `scripts/gen-licenses.sh` and committed, so the shipped app
 * always has a list and the build never depends on the network. */
const LINKS = [
  { label: "Dokumentation", url: "https://docs.noix.dev/printy/" },
  { label: "Quellcode", url: "https://github.com/NoiXdev/printy" },
  { label: "Alle Versionen", url: "https://github.com/NoiXdev/printy/releases" },
  { label: "Problem melden", url: "https://github.com/NoiXdev/printy/issues" },
];

export default function About(): JSX.Element {
  const [filter, setFilter] = useState("");

  // Read from the running binary rather than from package.json, for the same
  // reason the sidebar does: a copy in the frontend can drift from the version
  // the release workflow stamps into Cargo.toml.
  const version = useQuery({ queryKey: ["appVersion"], queryFn: api.getAppVersion });

  const filtered = useMemo<LicenseEntry[]>(() => {
    const q = filter.trim().toLowerCase();
    if (q.length === 0) return licenses;
    return licenses.filter((entry) => entry.name.toLowerCase().includes(q));
  }, [filter]);

  return (
    <section className="screen">
      <h1>Über Printy</h1>

      <div className="card">
        <Logo size={44} wordmark />
        <p style={{ marginTop: "0.9rem" }}>
          Legt Dateien aus überwachten Ordnern automatisch auf den Drucker.
        </p>
        <p className="helper">
          {version.data !== undefined ? `Version ${version.data}` : "Version wird gelesen …"}
        </p>
        <div className="folder-actions" style={{ marginTop: "0.75rem" }}>
          {LINKS.map((link) => (
            <button
              key={link.url}
              type="button"
              className="link-btn"
              onClick={() => {
                void openUrl(link.url);
              }}
            >
              {link.label}
            </button>
          ))}
        </div>
        <p className="helper" style={{ marginTop: "0.75rem" }}>
          Printy steht unter der MIT-Lizenz. Ein Werkzeug von noix.dev.
        </p>
      </div>

      <div className="card">
        <h2>Lizenzen</h2>
        {licenses.length === 0 ? (
          <p className="helper">Lizenzliste wird beim nächsten Build erzeugt.</p>
        ) : (
          <>
            <div className="field">
              <input
                className="input"
                type="text"
                value={filter}
                placeholder="Nach Name filtern …"
                aria-label="Lizenzen nach Name filtern"
                onChange={(e) => setFilter(e.target.value)}
              />
            </div>
            <p className="helper" style={{ marginTop: 0 }} data-testid="licence-count">
              {filtered.length} von {licenses.length} Einträgen
            </p>
            {filtered.length === 0 ? (
              <p className="empty-title" style={{ marginTop: "0.5rem" }}>
                Kein Treffer
              </p>
            ) : (
              <ul
                data-testid="licence-list"
                style={{
                  listStyle: "none",
                  margin: "0.5rem 0 0",
                  padding: 0,
                  maxHeight: "22rem",
                  overflowY: "auto",
                }}
              >
                {filtered.map((entry) => (
                  <li
                    key={`${entry.name}@${entry.version}`}
                    style={{
                      display: "flex",
                      alignItems: "center",
                      gap: "0.5rem",
                      flexWrap: "wrap",
                      padding: "0.45rem 0",
                      borderBottom: "1px solid var(--ink-08)",
                    }}
                  >
                    <span style={{ fontWeight: 600 }}>{entry.name}</span>
                    <span className="helper" style={{ margin: 0 }}>
                      · {entry.version} ·
                    </span>
                    <span className="badge">{entry.license}</span>
                  </li>
                ))}
              </ul>
            )}
          </>
        )}
      </div>
    </section>
  );
}
